# Generated by Django 3.0.3 on 2020-02-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterregister',
            old_name='firstnmae',
            new_name='firstname',
        ),
    ]
