# Generated by Django 3.0.3 on 2020-02-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20200213_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voterregister',
        ),
    ]
