# Generated by Django 3.0.3 on 2020-02-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voterregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='voteridcopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteridcopy', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='adhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
    ]
