# Generated by Django 3.0.3 on 2020-02-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteadmin', '0007_assembly'),
        ('voters', '0006_auto_20200219_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='voterregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('adharno', models.CharField(max_length=20)),
                ('voterid', models.CharField(max_length=20)),
                ('email', models.CharField(default='abc22', max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.assembly')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='voteridcopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteridcopy', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='adhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
    ]
