# Generated by Django 3.0.3 on 2020-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0007_adhar_photo_voteridcopy_voterregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregister',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
