# Generated by Django 3.0.3 on 2020-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0008_voterregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregister',
            name='confirmpassword',
            field=models.CharField(default='hugfyv', max_length=20),
        ),
    ]
