# Generated by Django 3.0.3 on 2020-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0009_voterregister_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterregister',
            name='confirmpassword',
            field=models.CharField(max_length=20),
        ),
    ]
