# Generated by Django 3.0.3 on 2020-02-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0010_auto_20200223_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterregister',
            name='confirmpassword',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
