# Generated by Django 3.0.3 on 2020-02-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0012_auto_20200223_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterregister',
            name='confirmpassword',
        ),
    ]
