# Generated by Django 3.0.3 on 2020-02-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0013_remove_voterregister_confirmpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adhar',
            new_name='voter_adhar',
        ),
        migrations.RenameModel(
            old_name='photo',
            new_name='voter_idcopy',
        ),
        migrations.RenameModel(
            old_name='voteridcopy',
            new_name='voter_photo',
        ),
        migrations.RenameField(
            model_name='voter_idcopy',
            old_name='photo',
            new_name='voteridcopy',
        ),
        migrations.RenameField(
            model_name='voter_photo',
            old_name='voteridcopy',
            new_name='photo',
        ),
    ]
