# Generated by Django 3.0.3 on 2020-03-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0014_auto_20200225_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter_idcopy',
            name='voterregisterid',
        ),
        migrations.RemoveField(
            model_name='voter_photo',
            name='voterregisterid',
        ),
        migrations.RemoveField(
            model_name='voterregister',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='voterregister',
            name='location',
        ),
        migrations.DeleteModel(
            name='voter_adhar',
        ),
        migrations.DeleteModel(
            name='voter_idcopy',
        ),
        migrations.DeleteModel(
            name='voter_photo',
        ),
        migrations.DeleteModel(
            name='voterregister',
        ),
    ]
