# Generated by Django 3.0.3 on 2020-03-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteadmin', '0009_symbol_symbolname'),
        ('voters', '0015_auto_20200303_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='voterregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('adharno', models.CharField(max_length=20)),
                ('voterid', models.CharField(max_length=20)),
                ('email', models.CharField(default='abc22', max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.assembly')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.district')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.landmark')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.state')),
            ],
        ),
        migrations.CreateModel(
            name='voter_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='voter_idcopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteridcopy', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='voter_adhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar', models.FileField(upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
    ]
