# Generated by Django 3.0.2 on 2020-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0016_voter_adhar_voter_idcopy_voter_photo_voterregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregister',
            name='secret_password',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
