# Generated by Django 3.0.2 on 2020-05-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20200428_2148'),
        ('voters', '0017_voterregister_secret_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='voter_share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_share', models.FileField(default='pending', upload_to='')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='voter_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='vote_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default=0, max_length=20)),
                ('voting_time', models.TimeField()),
                ('candidateregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateregister')),
            ],
        ),
    ]
