# Generated by Django 3.0.3 on 2020-02-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidateregister',
        ),
    ]
