# Generated by Django 3.0.3 on 2020-02-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_adhar_candidateregister_photo_voteridcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='proposertb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname1', models.CharField(max_length=20)),
                ('vid1', models.CharField(max_length=20)),
                ('pname2', models.CharField(max_length=20)),
                ('vid2', models.CharField(max_length=20)),
                ('candidateregisterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateregister')),
            ],
        ),
    ]
