# Generated by Django 3.0.3 on 2020-02-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_proposertb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposertb',
            old_name='vid1',
            new_name='voterid1',
        ),
        migrations.RenameField(
            model_name='proposertb',
            old_name='vid2',
            new_name='voterid2',
        ),
    ]
