# Generated by Django 3.0.3 on 2020-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20200225_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateregister',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
