# Generated by Django 3.0.3 on 2020-03-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_adhar_candidateregister_photo_proposertb_voteridcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='addprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=20)),
                ('work1', models.CharField(max_length=20)),
                ('work1photo', models.FileField(upload_to='')),
                ('work2', models.CharField(max_length=20)),
                ('work2photo', models.FileField(upload_to='')),
                ('work3', models.CharField(max_length=20)),
                ('work3photo', models.FileField(upload_to='')),
                ('achievements', models.CharField(max_length=20)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateregister')),
            ],
        ),
    ]
