# Generated by Django 3.0.3 on 2020-04-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_withdraw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='withdraw',
            new_name='withdraw_candidate',
        ),
    ]
