# Generated by Django 3.0.3 on 2020-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_auto_20200424_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addprofile',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='proposertb',
            name='candidateregisterid',
        ),
        migrations.AddField(
            model_name='addprofile',
            name='username',
            field=models.CharField(default='abc', max_length=20),
        ),
        migrations.AddField(
            model_name='proposertb',
            name='username',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
