# Generated by Django 3.0.2 on 2020-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_result_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateregister',
            name='count_vote',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
