# Generated by Django 3.0.3 on 2020-02-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateid', models.IntegerField(max_length=10)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
