# Generated by Django 3.0.3 on 2020-02-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_auto_20200213_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='district',
        ),
    ]
