# Generated by Django 3.0.3 on 2020-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=20)),
            ],
        ),
    ]
