# Generated by Django 3.0.3 on 2020-02-24 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.FileField(max_length=20, upload_to='')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.party')),
            ],
        ),
    ]
