# Generated by Django 3.0.3 on 2020-03-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_symbol_symbolname'),
    ]

    operations = [
        migrations.CreateModel(
            name='election_announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declarationdate', models.CharField(max_length=20)),
                ('nominationsubmissiondate', models.CharField(max_length=20)),
                ('nominationwithdrawndate', models.CharField(max_length=20)),
                ('campinestartingdate', models.CharField(max_length=20)),
                ('campineendingdate', models.CharField(max_length=20)),
                ('electiondate', models.CharField(max_length=20)),
                ('resultdate', models.CharField(max_length=20)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.assembly')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.district')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.landmark')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.state')),
            ],
        ),
    ]
