# Generated by Django 3.0.3 on 2020-03-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_election_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election_announcement',
            old_name='nominationwithdrawndate',
            new_name='nominationwithdrawdate',
        ),
    ]
