# Generated by Django 3.0.3 on 2020-03-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0011_auto_20200304_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_announcement',
            name='election_name',
            field=models.CharField(default='asd', max_length=20),
        ),
    ]
